messages:
  joinMessageOp: true

debug: false

rankup_price:
  Novato: 1000
  Membro: 5000
  Aprendiz: 10000
  Veterano: 15000

mobs_money: #Dinheiro Ganho por Kill
  zombie: 1
  skeleton: 1
mobs_chance: #Chance de Ganhar dinheiro por Kill
  zombie: 100
=======
messages:
  joinMessageOp: true

debug: false

rankup_price:
  Novato: 1000
  Membro: 5000
  Aprendiz: 10000
  Veterano: 15000

mobs_money: #Dinheiro Ganho por Kill
  zombie: 1
  skeleton: 1
mobs_chance: #Chance de Ganhar dinheiro por Kill
  zombie: 100
  skeleton: 100